services:
  - type: web
    name: nimbark-hrms
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 4 --bind 0.0.0.0:$PORT
    healthCheckPath: /healthz
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
